import { expect, test } from '@playwright/test'

test.describe('public acquisition workflow', () => {
  test('landing page and early access page render', async ({ page }) => {
    await page.goto('/landing-page')
    await expect(page.locator('body')).toContainText('Medellin Rewards')
    await expect(page.getByRole('heading', { name: /Gana Recompensas Increibles/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Elige Como Ganar/i })).toBeVisible()
    await expect(page.getByText('Membresia Regular')).toBeVisible()
    await expect(page.getByRole('heading', { name: /Tres pasos para empezar a ganar/i })).toBeVisible()
    await expect(page.getByText('Donde puedo usar mis Recompensas?')).toBeVisible()
    await expect(page.locator('select[aria-label]').first()).toBeVisible()
    await page.locator('select[aria-label]').first().selectOption('en')
    await expect(page.getByRole('heading', { name: /Earn Amazing Rewards/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Choose How You Earn/i })).toBeVisible()
    await expect(page.getByText('Regular Membership')).toBeVisible()
    await expect(page.getByRole('heading', { name: /Three steps to start earning/i })).toBeVisible()
    await expect(page.getByText('Where can I use my Rewards?')).toBeVisible()
    await expect(page.locator('header').getByRole('link', { name: /Businesses/i })).toHaveAttribute('href', '/business')
    await expect(page.getByText('You can use your Rewards with many partnered businesses')).toBeVisible()

    await page.goto('/invitation')
    await expect(page.locator('body')).toContainText(/Medell[ií]n Rewards/)
    await expect(page.locator('body')).toContainText(/Suscribirse|Subscribe/i)
    await page.getByRole('button', { name: /Suscribirse|Subscribe/i }).click()
    await page.getByRole('button', { name: /Suscribirse|Subscribe/i }).click()
    await expect(page.getByText(/Enter your WhatsApp number|Ingresa tu n.mero de WhatsApp/i)).toBeVisible()
    await expect(page.getByText(/Enter your email|Ingresa tu correo/i)).toBeVisible()
  })
})
