export const MEMBERSHIP_PRICE_CENTS = 2500
export const MEMBERSHIP_PRICE_USD = MEMBERSHIP_PRICE_CENTS / 100
export const MEMBERSHIP_REWARD_CREDIT_CENTS = 1000
export const MEMBERSHIP_REWARD_CREDIT_USD = MEMBERSHIP_REWARD_CREDIT_CENTS / 100
